<?xml version="1.0" encoding="UTF-8"?>
<!--
資料名稱: 臺灣出版新書預告書訊
收錄期間: 本資料與全國新書資訊網「書目下載/批次下載」每月同步更新，本次更新日期103年5月。
說　　明: 本資料集內容屬我國即將出版之新書，向國家圖書館國際標準書號中心申請國際標準書號（ISBN）之新書書目資訊。正式出版後時有異動，請以正式出版之書目資料為準。
-->
<!DOCTYPE Book [
 <!ELEMENT Book (書名, 作者, 出版單位, 版次, 出版年月, 標題, 適讀對象, 類號, ISBN)>
 <!ELEMENT 書名 (#PCDATA)>
 <!ELEMENT 作者 (#PCDATA)>
 <!ELEMENT 出版單位 (#PCDATA)>
 <!ELEMENT 版次 (#PCDATA)>
 <!ELEMENT 出版年月 (#PCDATA)>
 <!ELEMENT 標題 (#PCDATA)>
 <!ELEMENT 適讀對象 (#PCDATA)>
 <!ELEMENT 類號 (#PCDATA)>
 <!ELEMENT ISBN (#PCDATA)>
]>
<Books>
    <Book>
        <書名>舊巷</書名>
        <作者>李皇誼著</作者>
        <出版單位>萬卷樓</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <類號>848.6</類號>
        <ISBN>978-957-739-855-0 (平裝, NT$260, 203面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>老子道德經新譯暨心靈藥方</書名>
        <作者>林安梧著</作者>
        <出版單位>萬卷樓</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.道德經 2.注釋 </標題>
        <類號>121.311</類號>
        <ISBN>978-957-739-856-7 (平裝, NT$280, 205面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>&lt;&lt;楞嚴經&gt;&gt;大勢至菩薩「念佛圓通章」釋疑之研究</書名>
        <作者>果濱撰</作者>
        <出版單位>萬卷樓</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.密教部 </標題>
        <類號>221.94</類號>
        <ISBN>978-957-739-857-4 (精裝, NT$300, 197面, 24公分)</ISBN>
    </Book>
    <Book>
        <書名>做業務的200個超越</書名>
        <作者>王國華作</作者>
        <出版單位>海鴿文化</出版單位>
        <版次>一版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.銷售 2.銷售員 3.職場成功法 </標題>
        <類號>496.5</類號>
        <ISBN>978-986-5951-74-0 (平裝, NT$280, 224面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>圖解經濟學原理</書名>
        <作者>阿爾弗雷德.馬歇爾作; 賈開吉譯</作者>
        <出版單位>海鴿文化</出版單位>
        <版次>一版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.經濟學 </標題>
        <類號>550</類號>
        <ISBN>978-986-5951-75-7 (平裝, NT$480, 456面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>這些餐徹底改變了我</書名>
        <作者>廖欣儀作</作者>
        <出版單位>和平國際文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.食譜 2.健康飲食 3.減重 </標題>
        <類號>427.1</類號>
        <ISBN>978-986-5894-76-4 (平裝, NT$280, 156面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>看懂食品標示: 揪出潛藏地雷成分、化學添加物、反式脂肪的實戰筆記</書名>
        <作者>鄺易行作</作者>
        <出版單位>和平國際文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.食品添加物 2.食品衛生 </標題>
        <類號>463.11</類號>
        <ISBN>978-986-5894-77-1 (平裝, 144面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>食品科學概論</書名>
        <作者>曹欽玉等合著</作者>
        <出版單位>華格那企業</出版單位>
        <版次>四版</版次>
        <出版年月>103/01</出版年月>
        <標題>1.食品科學 </標題>
        <類號>463</類號>
        <ISBN>978-986-5828-79-0 (平裝, NT$320, 304面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>觀光暨餐旅消費者行為</書名>
        <作者>李宜靜等合著</作者>
        <出版單位>華格那企業</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.旅遊業 2.餐旅業 3.消費者行為 4.消費心理學 </標題>
        <類號>992.014</類號>
        <ISBN>978-986-5828-80-6 (平裝, NT$420, 376面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>早期印度佛教的知識論</書名>
        <作者>吳汝鈞著</作者>
        <出版單位>臺灣學生</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.佛教哲學 2.知識論 3.印度 </標題>
        <類號>220.11</類號>
        <ISBN>978-957-15-1608-0 (平裝, NT$350, 264面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>唯識學與精神分析: 以阿賴耶識與潛意識為主</書名>
        <作者>吳汝鈞著</作者>
        <出版單位>臺灣學生</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.唯識 2.佛教哲學 3.精神分析 </標題>
        <類號>220.123</類號>
        <ISBN>978-957-15-1609-7 (平裝, NT$620, 479面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>孫式太極拳拳架解析</書名>
        <作者>張大輝編著</作者>
        <出版單位>大展</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.太極拳 </標題>
        <類號>528.972</類號>
        <ISBN>978-986-346-012-1 (平裝, NT$220, 222面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>洗髓經健身術</書名>
        <作者>布援強著</作者>
        <出版單位>大展</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.氣功 2.養生 </標題>
        <類號>413.94</類號>
        <ISBN>978-986-346-013-8 (平裝附數位影音光碟, NT$250, 202面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>道教女神信仰研究</書名>
        <作者>莊宏誼主編</作者>
        <出版單位>輔大書坊</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.道教 2.女性 3.民間信仰 4.文集 </標題>
        <類號>230.7</類號>
        <ISBN>978-986-6221-93-4 (平裝, NT$350, 292面, 22公分)</ISBN>
    </Book>
    <Book>
        <書名>競賽實務技術報告: 維戈世界大學跆拳道錦標賽技術報告. 2010年第十一屆</書名>
        <作者>羅新明作</作者>
        <出版單位>輔大書坊</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.跆拳道 2.運動訓練 </標題>
        <類號>528.977</類號>
        <ISBN>978-986-6221-94-1 (平裝, NT$200, 123面, 22公分)</ISBN>
    </Book>
    <Book>
        <書名>眼見為憑</書名>
        <作者>林綠著</作者>
        <出版單位>魔豆文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-5987-40-4 (第3冊:平裝, NT$199, 256面, 20公分)</ISBN>
        <ISBN>978-986-5987-41-1 (第4冊:平裝, NT$199, 256面, 20公分)</ISBN>
    </Book>
    <Book>
        <書名>戲君侯. 卷一, 神偷志願</書名>
        <作者>雲外天都作</作者>
        <出版單位>紫宸社文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-281-613-4 (平裝, NT$250, 335面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>戲君侯. 卷二, 回不去了</書名>
        <作者>雲外天都作</作者>
        <出版單位>紫宸社文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-281-614-1 (平裝, NT$250, 335面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>紙貴金迷. 卷2, 展露頭角</書名>
        <作者>清楓聆心作</作者>
        <出版單位>紫宸社文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-281-615-8 (平裝, NT$250, 367面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>恬靜悠美: 楊興生的鄉土風情</書名>
        <作者>創價藝文中心委員會編輯部編輯</作者>
        <出版單位>勤宣文教基金會</出版單位>
        <出版年月>103/03</出版年月>
        <標題>1.油畫 2.畫冊 </標題>
        <類號>948.5</類號>
        <ISBN>978-986-89909-5-1 (平裝, 72面, 25X26公分)</ISBN>
    </Book>
    <Book>
        <書名>火鳥傳奇: 楚戈創作巡迴展</書名>
        <作者>創價藝文中心委員會編輯部編輯</作者>
        <出版單位>勤宣文教基金會</出版單位>
        <出版年月>103/03</出版年月>
        <標題>1.美術 2.作品集 </標題>
        <類號>902.33</類號>
        <ISBN>978-986-89909-6-8 (平裝, 72面, 25X26公分)</ISBN>
    </Book>
    <Book>
        <書名>安眠與愉悅</書名>
        <作者>羽田洋介主編</作者>
        <出版單位>貓咪予花兒工作室</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.失眠症 </標題>
        <類號>415.9983</類號>
        <ISBN>978-986-90312-7-1 (平裝, NT$300, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>發現金寶山之美: 金寶山攝影大賽. 第二屆</書名>
        <作者>張孟起撰文; 曹日章總編輯</作者>
        <出版單位>金寶山</出版單位>
        <出版年月>103/02</出版年月>
        <標題>1.攝影集 </標題>
        <類號>958.33</類號>
        <ISBN>978-957-28203-8-4 (精裝, NT$500, 84面, 25X26公分)</ISBN>
    </Book>
    <Book>
        <書名>俄屬遠東黃禍論: 身分、利益的解構與建構</書名>
        <作者>劉蕭翔著</作者>
        <出版單位>政大出版社</出版單位>
        <版次>初版</版次>
        <出版年月>103/01</出版年月>
        <標題>1.中俄關係 2.外交政策 3.建構主義 </標題>
        <類號>578.48</類號>
        <ISBN>978-986-6475-48-1 (平裝, NT$400, 320面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>向下扎根的操練</書名>
        <作者>姜俊旻著; 宛家禾譯</作者>
        <出版單位>校園書房</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.基督徒 2.靈修 </標題>
        <類號>244.93</類號>
        <ISBN>978-986-198-367-7 (精裝, NT$300, 247面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>田春禮臨床經驗集</書名>
        <作者>魏錦峰, 田雨河主編</作者>
        <出版單位>大展</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.中醫 2.臨床醫學 </標題>
        <類號>413.2</類號>
        <ISBN>978-986-346-014-5 (平裝, NT$230, 250面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>福音咖啡</書名>
        <作者>戴主誠主編</作者>
        <出版單位>上鋐書庫</出版單位>
        <出版年月>103/02</出版年月>
        <標題>1.聖經研究 2.生活指導 </標題>
        <類號>241.01</類號>
        <ISBN>978-986-89132-3-3 (平裝, 120面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>歷史檔案館. 2, 惡夢</書名>
        <作者>薇多莉亞.舒瓦著; 林零譯</作者>
        <出版單位>奇幻基地</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <類號>874.59</類號>
        <ISBN>978-986-5880-63-7 (平裝, NT$320, 379面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>Mcarky的零極限完美人像攝影術</書名>
        <作者>周明進, Kram Mcarky作</作者>
        <出版單位>城邦文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.人像攝影 2.攝影技術 </標題>
        <類號>953.3</類號>
        <ISBN>978-986-120-286-0 (平裝, NT$420, 192面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>新編體重控制學</書名>
        <作者>黃孟娟等合著</作者>
        <出版單位>華格那企業</出版單位>
        <版次>二版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.肥胖症 2.體重控制 3.減重 </標題>
        <類號>415.599</類號>
        <ISBN>978-986-5828-81-3 (平裝, NT$400, 352面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>社會企業經營管理論文集. 2014</書名>
        <作者>汪浩, 翟本瑞編著</作者>
        <出版單位>逢甲通識教育中心</出版單位>
        <出版年月>103/01</出版年月>
        <標題>1.非營利組織 2.文集 </標題>
        <類號>546.707</類號>
        <ISBN>978-986-5843-11-3 (精裝, 286面, 30公分)</ISBN>
    </Book>
    <Book>
        <書名>天下第一笑話之王. 1, 一見就笑</書名>
        <作者>張允中編著</作者>
        <出版單位>知青頻道</出版單位>
        <版次>第一版</版次>
        <出版年月>103/02</出版年月>
        <類號>856.8</類號>
        <ISBN>978-986-5699-00-0 (平裝, NT$159, 288面, 17公分)</ISBN>
    </Book>
    <Book>
        <書名>天下第一笑話之王. 2, 果然有笑</書名>
        <作者>張允中編著</作者>
        <出版單位>知青頻道</出版單位>
        <版次>第一版</版次>
        <出版年月>103/02</出版年月>
        <類號>856.8</類號>
        <ISBN>978-986-5699-01-7 (平裝, NT$159, 280面, 17公分)</ISBN>
    </Book>
    <Book>
        <書名>天下第一笑話之王. 3, 笑到流目屎</書名>
        <作者>張允中編著</作者>
        <出版單位>知青頻道</出版單位>
        <版次>第一版</版次>
        <出版年月>103/02</出版年月>
        <類號>856.8</類號>
        <ISBN>978-986-5699-02-4 (平裝, NT$159, 280面, 17公分)</ISBN>
    </Book>
    <Book>
        <書名>天下第一笑話之王. 4, 笑到凍未條</書名>
        <作者>張允中編著</作者>
        <出版單位>知青頻道</出版單位>
        <版次>第一版</版次>
        <出版年月>103/02</出版年月>
        <類號>856.8</類號>
        <ISBN>978-986-5699-03-1 (平裝, NT$159, 272面, 17公分)</ISBN>
    </Book>
    <Book>
        <書名>中華文明啟示錄</書名>
        <作者>欒樹軍作</作者>
        <出版單位>微塵工作坊</出版單位>
        <出版年月>103/03</出版年月>
        <標題>1.文明史 2.中華民族 3.言論集 4.中國 </標題>
        <類號>630</類號>
        <ISBN>978-986-89237-4-4 (平裝, NT$220, 240面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>日本寫真50年</書名>
        <作者>大竹昭子著; 黃大旺譯</作者>
        <出版單位>臉譜</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.攝影史 2.攝影師 3.日本 </標題>
        <類號>950.931</類號>
        <ISBN>978-986-235-342-4 (平裝, NT$400, 317面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>這樣吃,人生大混亂!: 你從來不知道的食物力</書名>
        <作者>Otto Wolff作; 戴君玲翻譯</作者>
        <出版單位>人智</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.健康飲食 2.食物 </標題>
        <類號>411.3</類號>
        <ISBN>978-986-87522-4-5 (平裝, NT$250, 144面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>彩色原子筆創意畫</書名>
        <作者>糖果嗡嗡作</作者>
        <出版單位>文房文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.原子筆 2.繪畫技法 </標題>
        <類號>948.9</類號>
        <ISBN>978-986-5910-40-2 (第1冊:平裝, NT$240, 128面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>宗鏡錄略講</書名>
        <作者>南懷瑾講述</作者>
        <出版單位>老古</出版單位>
        <版次>臺灣初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.禪宗 </標題>
        <類號>226.6</類號>
        <ISBN>978-986-6059-11-7 (第3冊:平裝, NT$350, 398面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>跑步者瑜伽聖經: 讓身體變得靈活平衡的瑜伽練習</書名>
        <作者>琴.卡奇著; 顧晶霞譯</作者>
        <出版單位>臺灣明名文化傳播</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.瑜伽 </標題>
        <類號>411.15</類號>
        <ISBN>978-986-88537-4-4 (平裝, NT$450, 232面, 22公分)</ISBN>
    </Book>
    <Book>
        <書名>六祖法寶壇經會意</書名>
        <作者>蘇俊源編著</作者>
        <出版單位>多識界圖書文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.六祖壇經 2.注釋 </標題>
        <類號>226.62</類號>
        <ISBN>978-986-6574-36-8 (平裝, 352面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>驚人的抗老養顏α-硫辛酸徹底了解!</書名>
        <作者>主婦と生活社編著; 張華英譯</作者>
        <出版單位>瑞昇文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.健康食品 2.營養 </標題>
        <類號>411.373</類號>
        <ISBN>978-986-5749-29-3 (平裝, NT$250, 63面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>這樣說,就能說進男人心坎裡. 3, 幸福女人必學的「攻心說話術」</書名>
        <作者>羅夫曼作</作者>
        <出版單位>太陽氏文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.兩性關係 </標題>
        <類號>544.7</類號>
        <ISBN>978-957-470-627-3 (平裝, NT$250, 240面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>如何訂做一個好學生</書名>
        <作者>Ken Bain著; 周念縈譯</作者>
        <出版單位>大塊文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.高等教育 2.教學法 </標題>
        <類號>525.03</類號>
        <ISBN>978-986-213-210-4 (精裝, NT$300, 328面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>管理其實越簡單越好</書名>
        <作者>李翔生編著</作者>
        <出版單位>讀品文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.領導者 2.企業管理 </標題>
        <類號>494.23</類號>
        <ISBN>978-986-5808-43-3 (平裝, NT$220, 223面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>電子商務程式設計</書名>
        <作者>丁致良著</作者>
        <出版單位>德豊文化</出版單位>
        <版次>二版</版次>
        <出版年月>103/01</出版年月>
        <標題>1.電子商務 2.電腦程式設計 </標題>
        <類號>490.29</類號>
        <ISBN>978-986-90417-1-3 (平裝, NT$300, 132面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>有效教學面面觀</書名>
        <作者>Gary D. Borich著; 郝永崴譯</作者>
        <出版單位>學富文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.教學法 2.班級經營 </標題>
        <類號>521.4</類號>
        <ISBN>978-986-5713-02-7 (平裝, NT$600, 456面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>文化脈動於視覺設計應用之探討</書名>
        <作者>賴怡臻著</作者>
        <出版單位>漢家</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.視覺設計 2.海報設計 3.文化 </標題>
        <類號>960</類號>
        <ISBN>978-986-6341-41-0 (平裝, 70面, 30公分)</ISBN>
    </Book>
    <Book>
        <書名>佛學指南</書名>
        <作者>丁福保編纂; 梅光羲節錄</作者>
        <出版單位>大乘精舍印經會</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.佛教 </標題>
        <類號>220</類號>
        <ISBN>978-986-5963-30-9 (平裝, 132面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>人生是可以改變的: 哥林多書信的信息</書名>
        <作者>陳南州著</作者>
        <出版單位>臺灣教會公報社</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.哥林多前書 2.哥林多後書 3.教牧學 </標題>
        <類號>245.2</類號>
        <ISBN>978-986-6331-91-6 (平裝, 371面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>不動產經紀相關法規概要</書名>
        <作者>陳俊合編著</作者>
        <出版單位>德明財經科大不動產與永續城鄉研究室</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.不動產經紀業 2.房地產法規 </標題>
        <類號>554.89023</類號>
        <ISBN>978-957-30175-6-1 (平裝, NT$450, 300面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>圖解沒有人這樣說財報: 只有常識和數字的直覺就學得會財務報表</書名>
        <作者>神田知宜著; 方瑜譯</作者>
        <出版單位>易博士文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.財務報表 </標題>
        <類號>495.47</類號>
        <ISBN>978-986-6434-56-3 (平裝, NT$300, 197面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>英文發音的10個規則</書名>
        <作者>Josephine Lin著</作者>
        <出版單位>易富文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.英語 2.發音 </標題>
        <類號>805.141</類號>
        <ISBN>978-986-5927-67-7 (平裝附光碟片, NT$349, 288面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>Mind Map Korean: 圖解韓國人每天必用的單字句型</書名>
        <作者>Naritha Sukpraman作</作者>
        <出版單位>漢宇國際文化</出版單位>
        <出版年月>103/04</出版年月>
        <標題>1.韓語 2.詞彙 3.會話 </標題>
        <類號>803.22</類號>
        <ISBN>978-986-228-219-9 (平裝附光碟片, NT$380, 419面, 19公分)</ISBN>
    </Book>
    <Book>
        <書名>心理畫2&amp;心理畫4合集</書名>
        <作者>嚴文華著</作者>
        <出版單位>宇河文化</出版單位>
        <版次>第一版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.繪畫心理學 </標題>
        <類號>940.14</類號>
        <ISBN>978-957-659-961-3 (平裝, NT$465, 626面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>當修復作為一種正義</書名>
        <作者>陳文珊著</作者>
        <出版單位>永望文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.基督教 2.文集 </標題>
        <類號>240.7</類號>
        <ISBN>978-986-5996-37-6 (平裝, 241面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>滋陰補陽不生病</書名>
        <作者>孔繁祥編著</作者>
        <出版單位>大都會文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.中醫 2.養生 </標題>
        <類號>413.21</類號>
        <ISBN>978-986-5719-04-3 (平裝, NT$320, 192面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>氣候變遷與美軍海外救援</書名>
        <作者>周力行著</作者>
        <出版單位>翰蘆圖書</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.軍事援助 2.災難救助 </標題>
        <類號>591.79</類號>
        <ISBN>978-986-5860-34-9 (平裝, NT$380, 250面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>雜食者的詛咒: 胖和你想的不一樣,當一卡路里不是一卡路里</書名>
        <作者>羅伯.魯斯提(Robert H. Lustig)作; 連緯晏譯</作者>
        <出版單位>大牌</出版單位>
        <版次>二版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.肥胖症 </標題>
        <類號>415.599</類號>
        <ISBN>978-986-5797-13-3 (平裝, NT$380, 320面, 22公分)</ISBN>
    </Book>
    <Book>
        <書名>禪問: 新時代修行的70個處方</書名>
        <作者>妙參著</作者>
        <出版單位>賽斯文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.禪宗 2.佛教修持 </標題>
        <類號>226.65</類號>
        <ISBN>978-986-6436-54-3 (平裝, NT$280, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>獨白</書名>
        <作者>東燁(穹風)著</作者>
        <出版單位>商周</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-272-539-9 (平裝, NT$200, 231面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>數據獵殺: 一場輸不起的全球網路戰爭</書名>
        <作者>東鳥作</作者>
        <出版單位>上奇資訊</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.資訊社會 2.網路社會 </標題>
        <類號>541.415</類號>
        <ISBN>978-986-5714-49-9 (平裝, 272面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>翼下之風</書名>
        <作者>廖效詮作</作者>
        <出版單位>廖效詮</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <類號>855</類號>
        <ISBN>978-957-43-1224-5 (平裝, NT$240, 240面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>一光年的距離有多遠</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-87-1 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>心的1/2</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-5970-88-8 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>愛上愛情</書名>
        <作者>曾煒, 解嬿嬿著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-89-5 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>我為歌狂</書名>
        <作者>解嬿嬿, 曾煒, 盧穎著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-90-1 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>喜歡你</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-91-8 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>星星的記號</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-92-5 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>夢想飛行里程之藍色換日線</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/04</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-93-2 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>夢想飛行里程之你是我的終點站嗎</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/04</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-94-9 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>米奇的甜心屋</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/04</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-95-6 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>魔術師</書名>
        <作者>曾煒著</作者>
        <出版單位>順達文化</出版單位>
        <版次>1版</版次>
        <出版年月>103/04</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5970-96-3 (平裝, NT$240, 256面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>弦歌雅樂</書名>
        <作者>邱宜文主編</作者>
        <出版單位>中華維德文化協會</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.詩歌吟唱 2.曲譜 </標題>
        <類號>915.18</類號>
        <ISBN>978-986-90420-0-0 (精裝附光碟片, NT$250, 72面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>秋天的懷念</書名>
        <作者>賈平凹, 宗璞著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-54-2 (平裝, NT$240, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>誰可以給誰幸福</書名>
        <作者>張之路, 饒雪漫著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-55-9 (平裝, NT$240, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>最後的藏羚群</書名>
        <作者>曹文軒, 沈石溪著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-56-6 (平裝, NT$240, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>樹上長出了小老鼠</書名>
        <作者>金波, 葛翠琳著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-57-3 (, NT$240, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>惡魔敲打巫婆的窗</書名>
        <作者>湯素蘭, 彭懿著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/04</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-58-0 (平裝, NT$240, 192面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>我被變成了黃色的花襖</書名>
        <作者>沈靜媛, 金波, 彭懿著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-59-7 (平裝, NT$200, 200面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>雲豹斑斑</書名>
        <作者>沈靜媛, 沈石溪, 牧鈴著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/02</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-60-3 (平裝, NT$200, 200面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>自己的天空</書名>
        <作者>沈靜媛, 李學斌, 黃春華著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-61-0 (平裝, NT$200, 200面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>跑進陽光裡</書名>
        <作者>沈靜媛, 曹文軒, 陳丹燕著</作者>
        <出版單位>黃山國際</出版單位>
        <版次>1版</版次>
        <出版年月>103/03</出版年月>
        <類號>859.6</類號>
        <ISBN>978-986-5849-62-7 (平裝, NT$200, 200面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>李元松老師往生十週年紀念集</書名>
        <作者>溫金柯主編</作者>
        <出版單位>現代禪淨土念佛會</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.佛教 2.文集 </標題>
        <類號>220.7</類號>
        <ISBN>978-986-90421-0-9 (精裝, 518面, 22公分)</ISBN>
    </Book>
    <Book>
        <書名>植.樹: 蔡獻友作品集</書名>
        <作者>吳守哲總編輯</作者>
        <出版單位>正修科大</出版單位>
        <出版年月>103/02</出版年月>
        <標題>1.複合媒材繪畫 2.畫冊 </標題>
        <類號>947.5</類號>
        <ISBN>978-986-7339-98-0 (平裝, 132面, 30公分)</ISBN>
    </Book>
    <Book>
        <書名>生命卑微不卑賤</書名>
        <作者>簡耀峰編著</作者>
        <出版單位>大拓文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.生命哲學 2.通俗作品 </標題>
        <類號>191.91</類號>
        <ISBN>978-986-5886-65-3 (平裝, NT$220, 218面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>背包客基本要會的日語便利句</書名>
        <作者>雅典日研所編著</作者>
        <出版單位>雅典文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.日語 2.自助旅行 3.會話 </標題>
        <類號>803.188</類號>
        <ISBN>978-986-5753-08-5 (平裝附光碟片, NT$230, 315面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>藝術史中的漢晉與唐宋之變</書名>
        <作者>石守謙, 顏娟英主編</作者>
        <出版單位>石頭</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.佛教藝術 2.藝術史 3.中國史 4.文集 </標題>
        <類號>224.5207</類號>
        <ISBN>978-986-6660-29-0 (平裝, 464面, 26公分)</ISBN>
    </Book>
    <Book>
        <書名>世界真奇妙: 千奇百怪的文明與人文奇觀</書名>
        <作者>賴士均編著</作者>
        <出版單位>智學堂文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.奇聞異象 </標題>
        <類號>297</類號>
        <ISBN>978-986-5819-28-6 (平裝, NT$220, 224面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>師道</書名>
        <作者>李枝桃著</作者>
        <出版單位>寶瓶文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.青少年教育 </標題>
        <類號>528.47</類號>
        <ISBN>978-986-5896-62-1 (平裝, NT$300, 288面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>虛線的惡意</書名>
        <作者>野澤尚著; 劉子倩譯</作者>
        <出版單位>讀癮</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>861.57</類號>
        <ISBN>978-986-90317-2-1 (平裝, NT$320, 318面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>善導大師的淨土思想</書名>
        <作者>淨宗法師講述</作者>
        <出版單位>淨土宗</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.淨土宗 2.佛教哲學 </標題>
        <類號>226.51</類號>
        <ISBN>978-986-5888-22-0 (精裝, 797面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>無聲的對話: 范晏暖作品集. 2012</書名>
        <作者>范晏暖作</作者>
        <出版單位>新樂園藝術空間</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.金屬工藝 2.雕塑 3.作品集 </標題>
        <類號>935</類號>
        <ISBN>978-986-82397-3-9 (平裝, NT$1000, 59面, 30公分)</ISBN>
    </Book>
    <Book>
        <書名>畫一本書給自己</書名>
        <作者>Fiona Watt作; 陳鴻銘譯</作者>
        <出版單位>楓葉社文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.插畫 2.繪畫技法 </標題>
        <類號>947.45</類號>
        <ISBN>978-986-6033-85-8 (平裝, NT$220, 128面, 29公分)</ISBN>
    </Book>
    <Book>
        <書名>臺灣人最常問的英文問題. 2, Quick Fix: EZ TALK總編嚴選特刊</書名>
        <作者>EZ叢書館編輯部作</作者>
        <出版單位>日月文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.英語 2.慣用語 3.俚語 </標題>
        <類號>805.123</類號>
        <ISBN>978-986-248-376-3 (平裝附光碟片, NT$350, 144面, 28公分)</ISBN>
    </Book>
    <Book>
        <書名>數位電影製作概論</書名>
        <作者>丁祈方著</作者>
        <出版單位>麗文文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/02</出版年月>
        <標題>1.電影製作 2.數位攝影 </標題>
        <類號>987.4</類號>
        <ISBN>978-957-748-555-7 (平裝, NT$500, 338面, 24公分)</ISBN>
    </Book>
    <Book>
        <書名>教育行政研究方法論</書名>
        <作者>秦夢群, 黃貞裕著</作者>
        <出版單位>五南</出版單位>
        <版次>二版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.教育行政 2.研究方法 </標題>
        <類號>526.031</類號>
        <ISBN>978-957-11-7530-0 (平裝, NT$400, 312面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>從「土改」到「反右」: 吳奔星一九五0年代日記</書名>
        <作者>吳奔星著; 吳心海編</作者>
        <出版單位>獨立作家</出版單位>
        <版次>一版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.中國史 2.知識分子 </標題>
        <類號>628.7</類號>
        <ISBN>978-986-5729-05-9 (平裝, NT$550, 462面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>救命飲食. 2, 等你真的生病了再說?</書名>
        <作者>T.柯林.坎貝爾,  霍華.賈可布森著</作者>
        <出版單位>柿子文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.營養 2.素食 3.健康飲食 </標題>
        <類號>411.3</類號>
        <ISBN>978-986-85908-3-0 (平裝, NT$420, 368面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>美味的記憶: 幸福Wendy的療癒廚房</書名>
        <作者>詹秀敏著</作者>
        <出版單位>原水文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.飲食 2.文集 </標題>
        <類號>427.07</類號>
        <ISBN>978-986-5853-34-1 (平裝, NT$320, 224面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>在臺南生活的一百個理由</書名>
        <作者>何芊澐著</作者>
        <出版單位>啟動文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.遊記 2.生活方式 3.臺南市 </標題>
        <類號>733.9/127.69</類號>
        <ISBN>978-986-89983-8-4 (平裝, NT$330, 100面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>當心!別被「英文騙語」拐了!</書名>
        <作者>鍾亞捷編著</作者>
        <出版單位>凱信</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.英語 2.慣用語 </標題>
        <類號>805.123</類號>
        <ISBN>978-986-5920-46-3 (平裝附光碟片, NT$320, 289面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>一筆畫: 五個概念加一支筆,信手畫出好作品</書名>
        <作者>吳霈媜著</作者>
        <出版單位>大塊文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.插畫 2.繪畫技法 </標題>
        <類號>947.45</類號>
        <ISBN>978-986-213-513-6 (平裝, NT$250, 150面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>超可愛黏土甜點飾品&amp;配件小物</書名>
        <作者>山田けい作; 林農凱譯</作者>
        <出版單位>楓書坊文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/04</出版年月>
        <標題>1.泥工遊玩 2.黏土 </標題>
        <類號>999.6</類號>
        <ISBN>978-986-5775-50-6 (平裝, NT$300, 79面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>妖怪都市. 3, 驚世暗黑組合</書名>
        <作者>一世風流著</作者>
        <出版單位>耕林</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-286-479-1 (平裝, NT$250, 253面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>圖解第一次買對房子就上手</書名>
        <作者>林姜文婷, 易博士編輯部作</作者>
        <出版單位>易博士文化</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <標題>1.不動產業 2.投資 </標題>
        <類號>554.89</類號>
        <ISBN>978-986-6434-57-0 (平裝, NT$320, 237面, 23公分)</ISBN>
    </Book>
    <Book>
        <書名>暴力仙姬. 2, 木之卷</書名>
        <作者>峨嵋著</作者>
        <出版單位>耕林</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-286-480-7 (平裝, NT$250, 335面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>本王在此. 2, 鳳凰天劫</書名>
        <作者>九鷺非香著</作者>
        <出版單位>耕林</出版單位>
        <版次>初版</版次>
        <出版年月>103/03</出版年月>
        <類號>857.7</類號>
        <ISBN>978-986-286-481-4 (平裝, NT$220, 287面, 21公分)</ISBN>
    </Book>
    <Book>
        <書名>王爺太壞,王妃太怪</書名>